---
title: "Traffic Data Analysis"
output: html_document
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(knitr)
library(caret)
library(corrgram)
library(pROC)
library(plyr)
library(caretEnsemble)
library(doMC)
registerDoMC(cores = 4)
```

```{r}
train_models <- function(data, methods){
  
  t <- list(
    obs= data %>% dplyr::select(-TARGET,-CONTRACT_KEY),
    class= (data %>% dplyr::select(TARGET))[,1]
  )

  set.seed(1234556)
  models <- caretList(
    x= t$obs,
    y= t$class,
    metric="ROC",
    preProcess=c( "center", "scale"),
    tuneList = list(
      rf= caretModelSpec(method="rf")
    ),
    continue_on_fail = T,
    trControl = trainControl(method = "repeatedcv",
                             number=5,
                             repeats = 1 ,
                             classProbs = TRUE,
                             savePredictions = "final",
                             summaryFunction= twoClassSummary,
                             allowParallel = TRUE
    )
  )
  
  return(models)
}

train_model_single_tune <- function(data, method, grid){
  
  t <- list(
    obs= data %>% dplyr::select(-TARGET,-CONTRACT_KEY),
    class= (data %>% dplyr::select(TARGET))[,1]
  )

  set.seed(1234556)
  model <- train(
    x= t$obs,
    y= t$class,
    preProcess=c( "center", "scale"),
    method=method,
    metric="ROC",
    trControl = trainControl(method="LGOCV", number=1, classProbs = T, summaryFunction = twoClassSummary, allowParallel = TRUE),
    tuneGrid = grid
  )
  
  return(model)
}

train_model_no_tune <- function(data, method, grid){
  
  t <- list(
    obs= data %>% dplyr::select(-TARGET,-CONTRACT_KEY),
    class= (data %>% dplyr::select(TARGET))[,1]
  )

  set.seed(1234556)
  model <- train(
    x= t$obs,
    y= t$class,
    preProcess=c( "center", "scale"),
    method=method,
    trControl = trainControl(method="none",allowParallel = TRUE),
    tuneGrid = grid
  )
  
  return(model)
}

predict_and_create_submission <- function(model, test_data){
  
  test_data_without_contract_key <- test_data %>% dplyr::select(-CONTRACT_KEY)
  CONTRACT_KEYS <- (test_data %>% dplyr::select(CONTRACT_KEY))[,1] %>% as.factor
  predictions <- predict(model, test_data_without_contract_key)
  
  predictions <- predictions %>% sapply(function(x){return(ifelse(x == "X0", 0,1))})
  
  submission <- data.frame(
    CONTRACT_KEY = CONTRACT_KEYS,
    PREDICTED_TARGET = predictions
  )
  
  write.csv(submission,quote=FALSE,row.names=FALSE, file= paste("submissions/", Sys.time(), ".csv", sep=""))
  
  return(submission)
}
```

```{r eval=FALSE}
#ONLY USED ONCE TO CREATE THE USAGE ESTIMATED COLUMN

calculate_month_estimate <- function(u1,u2,u3,u4,u5){
  d <- data.frame(
    x = (1:5),
    y =c(u1,u2,u3,u4,u5)
  )
  p <- predict(lm(y~x, data=d), data.frame(x=c(6)))[[1]]
  return(p)
}

train_es <- train_data %>% rowwise() %>% do(ES=calculate_month_estimate(.$X206_USAGE, .$X207_USAGE, .$X208_USAGE, .$X209_USAGE,.$X210_USAGE)) %>% summarise(ES=ES)
train_es <- data.frame(ES = train_es$ES %>% unlist)
write.csv(train_es, quote=FALSE,row.names=FALSE, file="./data/train_estimated.csv")

test_es <- test_data %>% rowwise() %>% do(ES=calculate_month_estimate(.$X206_USAGE, .$X207_USAGE, .$X208_USAGE, .$X209_USAGE,.$X210_USAGE)) %>% summarise(ES=ES)
test_es <- data.frame(ES = test_es$ES %>% unlist)
write.csv(test_es, quote=FALSE,row.names=FALSE, file="./data/test_estimated.csv")
```


```{r}
#roaming_data <- read.csv("data/roaming_monthly.csv")
contract_data <- read.csv("data/contract_clean.csv")
test_data <- read.csv("data/test.csv")
train_data <- read.csv("data/train.csv")
#daily_aggregate <- read.csv("data/daily_aggregate.csv")
train_estimate_data <- read.csv("data/train_estimated.csv")
train_data$ES <- train_estimate_data$ES
test_estimate_data <- read.csv("data/test_estimated.csv")
test_data$ES <- test_estimate_data$ES
rm(train_estimate_data)
rm(test_estimate_data)
```


```{r}
parts <- createDataPartition(train_data$TARGET, p=0.75, list=F)
validate_data <- train_data[-parts,]
train_data <- train_data[parts,]
rm(parts)
```


```{r}
prepare_dataset_one_hot <- function(data, is_train) {
  ret_data <- data
  
  ret_data <- inner_join(ret_data, contract_data, by="CONTRACT_KEY") 
  
  ret_data <- ret_data %>% dplyr::select(-X, -HANDSET_NAME, -RATE_PLAN, -VALUE_SEGMENT)
  ret_data <- model.matrix(~. -1, data=ret_data, fullRank=F) %>% as.data.frame
  
  # FIXING THE AGE
  ret_data[ret_data$AGE == 99,]$AGE <- (ret_data[ret_data$AGE != 99,]$AGE %>% median)
  
  
  # Adding Some cols
  ret_data <- ret_data %>% mutate(USAGE_MEAN=(X206_USAGE+X207_USAGE+X208_USAGE+X209_USAGE+X210_USAGE)/5)
  
  if(is_train){
    
    ret_data <- ret_data %>% mutate(TARGET=as.factor(TARGET))
    levels(ret_data$TARGET) <- make.names(levels(factor(ret_data$TARGET)))
    
    # Drop UNNEEDED COLUMNS
    ret_data <- ret_data %>% dplyr::select(-ends_with("_SESSION_COUNT"))
    #ret_data <- ret_data %>% dplyr::select(-starts_with("SESSIONS_"))
    #ret_data <- ret_data %>% dplyr::select(-matches("X2"))
    
    
    # Removing almost zero variance variables
    nzv <- nearZeroVar(ret_data, names=TRUE)
    nzv <- nzv [! nzv %in% c("TARGET")]
    #ret_data <- ret_data %>% dplyr::select(-one_of(nzv))
    
    # Removing highly correlated features
    #descrCor <- cor(ret_data %>% dplyr::select(-TARGET))
    #highlyCorDescr <- findCorrelation(descrCor, cutoff = .90, names=TRUE)
    #ret_data <- ret_data %>% dplyr::select(-one_of(highlyCorDescr))
    
    # Removing linearly corelated values
    #lc <- findLinearCombos(ret_data %>% dplyr::select(-TARGET))
    
    #if(!is.null(lc$remove)){
    #  ret_data <- ret_data[, -lc$remove]
    #}
  }
  
  return(ret_data)
}

prepare_dataset <- function(data, is_train) {
  ret_data <- data
  
  ret_data <- inner_join(ret_data, contract_data, by="CONTRACT_KEY") 
  ret_data <- ret_data %>% dplyr::select(-X)
  
  # FIXING THE AGE
  ret_data[ret_data$AGE == 99,]$AGE <- (ret_data[ret_data$AGE != 99,]$AGE %>% median)
  
  # Adding Some cols
  ret_data <- ret_data %>% mutate(USAGE_MEAN=(X206_USAGE+X207_USAGE+X208_USAGE+X209_USAGE+X210_USAGE)/5)
  ret_data <- ret_data %>% mutate(USAGE_DIFF=X210_USAGE-X206_USAGE)
  
  ret_data <- ret_data %>% mutate(USAGE_FARGHAL=as.factor(ES > 0.9*USAGE_MEAN + 500))
  ret_data <- ret_data %>% mutate(USAGE_VARIANCE=(((X206_USAGE - USAGE_MEAN)^2 + (X207_USAGE - USAGE_MEAN)^2 + (X208_USAGE - USAGE_MEAN)^2 + (X209_USAGE - USAGE_MEAN)^2 + (X210_USAGE - USAGE_MEAN)^2)/5)^0.5)
  
  ret_data$RATE_PLAN <- ret_data$RATE_PLAN %>% as.character %>% sapply(function(x) ifelse(grepl("enterprise|business", tolower(x)), "Business", x)) %>% as.factor
  
  if(is_train){
    
    ret_data <- ret_data %>% filter(USAGE_MEAN < 17500)
    ret_data <- ret_data %>% filter(ES < 25000)
    ret_data <- ret_data %>% mutate(TARGET=as.factor(TARGET))
    levels(ret_data$TARGET) <- make.names(levels(factor(ret_data$TARGET)))
    
    # Drop UNNEEDED COLUMNS
    #ret_data <- ret_data %>% dplyr::select(-ends_with("_SESSION_COUNT"))
    #ret_data <- ret_data %>% dplyr::select(-starts_with("SESSIONS_"))
    ret_data <- ret_data %>% dplyr::select(-matches("X20"))
    
    # Removing almost zero variance variables
    nzv <- nearZeroVar(ret_data, names=TRUE)
    nzv <- nzv [! nzv %in% c("TARGET")]
    #ret_data <- ret_data %>% dplyr::select(-one_of(nzv))
    
    # Removing highly correlated features
    #descrCor <- cor(ret_data %>% dplyr::select(-TARGET))
    #highlyCorDescr <- findCorrelation(descrCor, cutoff = .90, names=TRUE)
    #ret_data <- ret_data %>% dplyr::select(-one_of(highlyCorDescr))
    
    # Removing linearly corelated values
    #lc <- findLinearCombos(ret_data %>% dplyr::select(-TARGET))
    
    #if(!is.null(lc$remove)){
    #  ret_data <- ret_data[, -lc$remove]
    #}
  }
  
  return(ret_data)
}

train_transformed_data <- prepare_dataset(train_data, TRUE)
test_transformed_data <- prepare_dataset(test_data, FALSE)
test_transformed_data <- test_transformed_data[, names(test_transformed_data) %in% (train_transformed_data %>% names)]

validate_transformed_data <- prepare_dataset(validate_data, FALSE)
validate_transformed_data <- validate_transformed_data[, names(validate_transformed_data) %in% (train_transformed_data %>% names)]
validate_transformed_data <- validate_transformed_data %>% mutate(TARGET=as.factor(TARGET))
levels(validate_transformed_data$TARGET) <- make.names(levels(factor(validate_transformed_data$TARGET)))

train_transformed_data %>%str
```


```{r}
print_auc <- function(x){
  print(x$method)
  p <- predict(x, validate_transformed_data %>% dplyr::select(-TARGET,-CONTRACT_KEY))
  print(auc(as.numeric(validate_transformed_data$TARGET), as.numeric(p)))
}


nb_model <- train_model_no_tune(train_transformed_data, "nb", expand.grid(fL=0, usekernel=T, adjust=1))
print_auc(nb_model)

nb_model <- train_model_single_tune(train_transformed_data, "rpart", NULL)
print_auc(nb_model)

knn_model <- train_model_no_tune(train_transformed_data, "knn", expand.grid(k=9))
print_auc(knn_model)

rf_model <- train_model_no_tune(train_transformed_data, "rf", expand.grid(mtry=3))
print_auc(rf_model)

models %>% sapply(print_auc)

stackControl <- trainControl(method="repeatedcv", number=5, repeats=3, savePredictions=TRUE, classProbs=TRUE, summaryFunction = twoClassSummary)
ens <- caretStack(models, metric="ROC", trControl=stackControl, method="glm")

p <- predict(ens, validate_transformed_data %>% dplyr::select(-TARGET,-CONTRACT_KEY))
print(auc(as.numeric(validate_transformed_data$TARGET), as.numeric(p)))

modelCor(resamples(models))

submission <- predict_and_create_submission(nb_model, test_transformed_data)
```